import {
  ClerkProvider,
} from "@clerk/nextjs";
import "./globals.css";
import PageHeader from "@/components/page-header";

export const metadata = {
  title: "Feedback Saas Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <PageHeader />
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
