/* eslint-disable @typescript-eslint/no-namespace */
import {
  ClerkProvider,
} from "@clerk/nextjs";
import "./globals.css";
import PageHeader from "@/components/page-header";

import Script from "next/script";

export const metadata = {
  title: "Feedback Saas Dashboard",
  description: "Generated by create next app",
};
declare global {
  namespace JSX {
    interface IntrinsicElements {
      ['my-widget']: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
    }
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Script src="https://feedback-widget-lyart.vercel.app/widget.umd.js"></Script>
        <body>

          <Script src="https://feedback-widget-lyart.vercel.app/widget.umd.js"></Script>
          <my-widget project-id="15"></my-widget>
          <PageHeader />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
